src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SongRepository::class)]
class Song
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $length_second = null;

    #[ORM\ManyToOne(inversedBy: 'songs')]
    private ?Album $album = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLengthSecond(): ?int
    {
        return $this->length_second;
    }

    public function setLengthSecond(int $length_second): static
    {
        $this->length_second = $length_second;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): static
    {
        $this->album = $album;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserRegisterForm;
use App\Mail\UserSubscribedConfirmation;
use App\Repository\GenreRepository;
use App\Repository\SongRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Attribute\Route;


final class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(SongRepository $songRepository): Response
    {
        $songs = $songRepository->findAll();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'songs' => $songs
        ]);
    }

    #[Route('/users', name: 'users')]
    public function users(UserRepository $userRepository,Request $request,EntityManagerInterface $em,UserSubscribedConfirmation $userSubscribedConfirmation): Response
    {
        $users = $userRepository->findAll();
        $userSuscriber = new User();
        $userform = $this->createForm(UserRegisterForm::class,$userSuscriber);
        $userform->handleRequest($request);


        if ($userform->isSubmitted() && $userform->isValid()) {
            $em->persist($userSuscriber);
            $em->flush();

            $this->addFlash('success','Votre inscription a bien été prise en compte');

            $userSubscribedConfirmation->send($userSuscriber);
            
            return $this->redirectToRoute('users');
        }

        return $this->render('home/users.html.twig', [
            'controller_name' => 'HomeController',
            'users' => $users,
            'form'=>$userform
        ]);
    }


}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HomePage{% endblock %}

{% block body %}

<h1>Better Than Deezer</h1>

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Groupe</th>
            <th>Album</th>
            <th>Genre</th>
            <th>Durée</th>
        </tr>
    </thead>
    <tbody>
        {% for song in songs %}
            <tr>
                <td>{{ song.name }}</td>
                <td><a href="{{path('artists',{ id: song.album.artist.id })}}">{{ song.album.artist.name }}</a></td>
                <td><a href="{{path('albums',{ id: song.album.id })}}">{{ song.album.name }}</a></td>
                <td><a href="{{path('genres',{ id: song.album.artist.genre.id })}}">{{ song.album.artist.genre.name }}</a></td>
                <td>{% set minutes = song.lengthSecond // 60 %}
                    {% set seconds = song.lengthSecond % 60 %}
                    {% if seconds<10 %}
                    {% set seconds = "0" ~ seconds %} 
                    {% endif %}
                    {{ minutes }}m {{ seconds }}s</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune chanson trouvée.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/home/users.html.twig
{% extends 'base.html.twig' %}

{% block title %}Userpage{% endblock %}

{% block body %}

<h1>Better Than Deezer</h1>
<div>{{form(form)}}
</div>

<ul >
{% for user in users %}
<li>{{user.email}}</li>

{% endfor %}
</ul>
{% endblock %}