src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtistRepository::class)]
class Artist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $member_number = null;

    #[ORM\ManyToOne(inversedBy: 'artists')]
    private ?Genre $genre = null;

    /**
     * @var Collection<int, Album>
     */
    #[ORM\OneToMany(targetEntity: Album::class, mappedBy: 'artist')]
    private Collection $albums;

    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMemberNumber(): ?int
    {
        return $this->member_number;
    }

    public function setMemberNumber(?int $member_number): static
    {
        $this->member_number = $member_number;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): static
    {
        if (!$this->albums->contains($album)) {
            $this->albums->add($album);
            $album->setArtist($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): static
    {
        if ($this->albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getArtist() === $this) {
                $album->setArtist(null);
            }
        }

        return $this;
    }
}

src/Controller/SpecificController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Entity\Artist;
use App\Entity\Genre;
use App\Repository\AlbumRepository;
use App\Repository\ArtistRepository;
use App\Repository\GenreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class SpecificController extends AbstractController
{
    #[Route('/artists/{id}', name: 'artists')]
    public function artists(Artist $artist): Response
    {
        return $this->render('specific/artists.html.twig', [
            'controller_name' => 'SpecificController',
            'artist' => $artist
        ]);
    }

    #[Route('/albums/{id}', name: 'albums')]
    public function albums(Album $album): Response
    {
        return $this->render('specific/albums.html.twig', [
            'controller_name' => 'SpecificController',
            'album' => $album
        ]);
    }

    #[Route('/genres/{id}', name: 'genres')]
    public function genres(Genre $genre): Response
    {
        return $this->render('specific/genres.html.twig', [
            'controller_name' => 'SpecificController',
            'genre'=>$genre
        ]);
    }
}

templates/specific/albums.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album Page{% endblock %}

{% block body %}
<div class="entity-container">
<h2>{{album.name}}</h2>
    <p>Date de parution de l'album : {{album.createdAt|date('d/m/Y')}}</p>
    
    
</hgroup>

    <a href="{{path('artists',{ id: album.artist.id })}}">{{album.artist.name}}</a>
</div>
<hgroup>
    

{% endblock %}

templates/specific/artists.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist Page{% endblock %}

{% block body %}

<div class="entity-container">
<hgroup>
    <h2>{{artist.name}}</h2>
    <p>Nombre albums :{{artist.albums|length}}</p>
    
    
</hgroup>

    <p>{{artist.description}}</p>
    <p>{{artist.memberNumber}} membres dans ce groupe</p>
    <h3><a href="{{path('genres',{id : artist.genre.id})}}">{{artist.genre.name}}</a></h3>

</div>



{% endblock %}

templates/specific/genres.html.twig
{% extends 'base.html.twig' %}

{% block title %}Genre page{% endblock %}

{% block body %}

<h1>Artistes dans la catégorie {{genre.name}}</h1>

<ul class="artists-list">
{% for artist in genre.artists %}
<li><a href="{{path('artists',{ id: artist.id })}}">{{ artist.name }}</a></li>

{% endfor %}
</ul>

{% endblock %}